set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/vundle'

Plugin 'scrooloose/nerdtree'
Plugin 'xuyuanp/nerdtree-git-plugin'
Plugin 'itchyny/lightline.vim'
Plugin 'Yggdroot/indentLine'
Plugin 'valloric/youcompleteme'
Plugin 'xuhdev/vim-latex-live-preview'

" Colorschemes
Plugin 'altercation/vim-colors-solarized'
Plugin 'drewtempelmeyer/palenight.vim'

call vundle#end()

" Set cache directory
set viminfo+=n~/.cache/vim/viminfo

" Some basic defaults
syntax enable
filetype plugin indent on

" Relative line numbering
set number relativenumber

" Splits open at the bottom and right, which is non-retarded, unlike vim defaults.
set splitbelow splitright

" Set behaviour for tab
set tabstop=4
set shiftwidth=4
set expandtab
set list lcs=tab:\|\ 

" Highlight search as they are typed
set incsearch
set hlsearch

" Start scrolling before reaching buffer end
set scrolloff=8

" Colorscheme
set background=dark
" let g:solarized_termcolors = 256
colorscheme palenight

" Status bar
let g:lightline = { 'colorscheme': 'palenight' }

" YouCompleteMe autocomplete
let g:ycm_filetype_blacklist = { 'tex': 1 }
let g:ycm_autoclose_preview_window_after_insertion = 1

" LaTeX live preview for MacOS
let g:livepreview_previewer = 'open -a Preview'
let g:livepreview_cursorhold_recompile = 0

" Open NERDTree automatically when vim is opened in a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Automatically deletes all trailing whitespace and newlines at end of file on save.
" autocmd BufWritePre * %s/\s\+$//e
" autocmd BufWritepre * %s/\n\+\%$//e

nmap <C-n>t :NERDTreeToggle<CR>
nmap <C-n>f :NERDTreeFind<CR>
nmap <C-p>i :PluginInstall<CR>

" Split mapping
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
