set nocompatible
filetype off    " Required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/vundle'

Plugin 'scrooloose/nerdtree'
Plugin 'xuyuanp/nerdtree-git-plugin'
Plugin 'itchyny/lightline.vim'
Plugin 'Yggdroot/indentLine'
" Plugin 'valloric/youcompleteme'

Plugin 'altercation/vim-colors-solarized'
Plugin 'dracula/vim'
Plugin 'sonph/onehalf', {'rtp': 'vim/'}
Plugin 'bluz71/vim-nightfly-guicolors'

call vundle#end()

set viminfo+=n~/.cache/vim/viminfo

if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

set termguicolors
set number relativenumber
syntax enable
set tabstop=4
set shiftwidth=4
set background=dark
let g:solarized_termcolors = 256
colorscheme solarized
" let g:dracula_colorterm=0
" colorscheme dracula
" colorscheme onehalfdark
" colorscheme nightfly

set list lcs=tab:\|\ 
" let g:lightline = { 'colorscheme': 'onehalfdark' }
" let g:lightline = { 'colorschem': 'nightfly' }
" let g:lightline = { 'colorscheme': 'dracula' }
let g:lightline = { 'colorscheme': 'solarized' }

filetype plugin indent on " Required

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

nmap <C-n> :NERDTreeToggle<CR>
nmap <C-p><C-i> :PluginInstall<CR>

" Split mapping
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
