#!/bin/sh

# Git
alias g="git"
alias gs="g s"
alias gp="g p"
alias gpu="g pu"
alias gpo="g po"
alias gc="g c"
alias gone="g one"
alias ga="g a"
alias gd="g d"

# System
alias ..="cd .."
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias ls="ls -G"
alias ll="ls -alhF"
alias la="ls -A"
alias l="ls -CF"
alias ccat="highlight --out-format=ansi"
alias ns="nvidia-smi"

# Dev
alias activate="source venv/bin/activate"
alias cv="cd ~/Dev/CV && activate"
alias plt="rsync -azP --delete virajs@lotus.cs.colostate.edu:~/Dev/CV/plots/ plots"
alias vi="vim"
alias tmux="tmux -f $HOME/.config/tmux/tmux.conf"
alias tas="tmux attach-session -t"

# Terminal tomfoolery
alias rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"
