#!/bin/sh

# SSH login for CSU Workstations
csu() {
    if [ $# -eq 0 ];then
        open -a "Google Chrome" https://www.cs.colostate.edu/~info/cuda_machines.txt;
    elif [ $# -eq 1 ];then
        ssh -X virajs@${1}.cs.colostate.edu;
    elif [ $# -eq 2 ];then
        ssh -X ${1}@${2}.cs.colostate.edu;
    fi
}

csuj() {
    p=8888
    [ "$#" = 2 ] && p="$2"
    ssh -L ${p}:localhost:${p} virajs@${1}.cs.colostate.edu
}

ta() {
    if [ $# -eq 0 ]; then
        csu cs253 salem;
    elif [ $# -gt 1 ]; then
        echo "Usage: $0 <machine-name>";
    else
        csu cs253 $1;
    fi
}

jn() {
    jupyter notebook --no-browser --port=${1}
}
